sudo: false
language: node_js
cache: yarn
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
matrix:
  include:
    - node_js: "lts/*"
      env: LINT=true
script:
  - 'if [ -n "${LINT-}" ]; then yarn run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then yarn run test-ci ; fi'
after_success:
  - yarn run coverage
