environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "4"

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

install:
  - ps: Install-Product node $env:node_version
  - yarn install

matrix:
  fast_finish: true

build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm run test-only

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
